import { useRef } from "react";
import { motion, useInView } from "motion/react";
import { ImageWithFallback } from "./figma/ImageWithFallback";

const galleryImages = [
  {
    src: "https://images.unsplash.com/photo-1768610284895-4ab037b60d16?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoaWdoJTIwZmFzaGlvbiUyMGVkaXRvcmlhbCUyMGJsYWNrJTIwb3V0Zml0JTIwbW9kZWwlMjBjaW5lbWF0aWN8ZW58MXx8fHwxNzc4MTY2MzE1fDA&ixlib=rb-4.1.0&q=80&w=1080",
    alt: "High fashion editorial black outfit",
    label: "STUDIO EDITORIAL",
    style: "row-span-2",
  },
  {
    src: "https://images.unsplash.com/photo-1774897795863-679e3a2826a7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmYXNoaW9uJTIwbW9kZWwlMjBlZGl0b3JpYWwlMjBtaW5pbWFsaXN0JTIwYmxhY2slMjB0dXJ0bGVuZWNrfGVufDF8fHx8MTc3ODE2NjMxOHww&ixlib=rb-4.1.0&q=80&w=1080",
    alt: "Fashion model minimalist turtleneck",
    label: "MINIMALIST SERIES",
    style: "",
  },
  {
    src: "https://images.unsplash.com/photo-1758749646094-606f23edaef6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsdXh1cnklMjBmYXNoaW9uJTIwZWRpdG9yaWFsJTIwbW9kZWwlMjBlbGVnYW50JTIwZ293biUyMGRyYW1hdGljJTIwbGlnaHRpbmd8ZW58MXx8fHwxNzc4MTY2MzE5fDA&ixlib=rb-4.1.0&q=80&w=1080",
    alt: "Luxury fashion editorial elegant gown",
    label: "HAUTE COUTURE",
    style: "",
  },
  {
    src: "https://images.unsplash.com/photo-1766951087359-fe48ea4f2796?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmYXNoaW9uJTIwbW9kZWwlMjBlZGl0b3JpYWwlMjBzdWl0JTIwb3ZlcnNpemVkJTIwc2lsaG91ZXR0ZXxlbnwxfHx8fDE3NzgxNjYzMTl8MA&ixlib=rb-4.1.0&q=80&w=1080",
    alt: "Fashion model editorial oversized suit",
    label: "POWER DRESSING",
    style: "col-span-2",
  },
  {
    src: "https://images.unsplash.com/photo-1764698072685-f01c10bd2dca?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmYXNoaW9uJTIwbW9kZWwlMjBwb3J0cmFpdCUyMGRyYW1hdGljJTIwc2hhZG93JTIwc3R1ZGlvfGVufDF8fHx8MTc3ODE2NjMxOXww&ixlib=rb-4.1.0&q=80&w=1080",
    alt: "Fashion model portrait dramatic shadow",
    label: "SHADOW PORTRAIT",
    style: "",
  },
];

export function GallerySection() {
  const ref = useRef<HTMLDivElement>(null);
  const inView = useInView(ref, { once: true, margin: "-80px" });

  return (
    <section ref={ref} className="py-32 lg:py-48 overflow-hidden" id="gallery" style={{ background: "#0A0908" }}>
      <div className="max-w-[1440px] mx-auto px-8 md:px-12 lg:px-16">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={inView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.9, ease: [0.22, 1, 0.36, 1] }}
          className="mb-16 lg:mb-20 flex flex-col lg:flex-row lg:items-end lg:justify-between gap-6"
        >
          <div>
            <div className="flex items-center gap-3 mb-5">
              <div className="h-px w-8 bg-[#C4BDB6]/40" />
              <span style={{ fontFamily: "var(--font-ui)", fontSize: "10px", color: "rgba(196,189,182,0.5)", letterSpacing: "0.22em" }}>
                GENERATED WORKS
              </span>
            </div>
            <h2
              className="text-[#F5F2EE]"
              style={{
                fontFamily: "var(--font-editorial)",
                fontSize: "clamp(38px, 4.5vw, 62px)",
                fontWeight: 300,
                lineHeight: "1.1",
              }}
            >
              Editorial imagery,
              <br />
              <em className="text-[#C4BDB6]" style={{ fontStyle: "italic" }}>generated by AI.</em>
            </h2>
          </div>
          <div className="max-w-xs">
            <p style={{ fontFamily: "var(--font-ui)", fontSize: "14px", color: "rgba(196,189,182,0.45)", lineHeight: "1.7", fontWeight: 300 }}>
              Every image in this gallery was generated from a simple product photograph using Norch.
            </p>
            <a
              href="#"
              className="inline-flex items-center gap-2 mt-4 hover:gap-3 transition-all duration-300"
              style={{ fontFamily: "var(--font-ui)", fontSize: "11px", color: "rgba(196,189,182,0.6)", letterSpacing: "0.14em" }}
            >
              VIEW FULL GALLERY
              <span className="text-[#C4BDB6]">→</span>
            </a>
          </div>
        </motion.div>

        {/* Grid */}
        <div className="grid grid-cols-2 lg:grid-cols-3 gap-3 lg:gap-4 auto-rows-[280px] lg:auto-rows-[360px]">
          {galleryImages.map((img, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 30 }}
              animate={inView ? { opacity: 1, y: 0 } : {}}
              transition={{ duration: 0.8, delay: i * 0.1, ease: [0.22, 1, 0.36, 1] }}
              className={`group relative overflow-hidden ${img.style}`}
              style={{ borderRadius: "2px" }}
            >
              <ImageWithFallback
                src={img.src}
                alt={img.alt}
                className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105"
              />

              {/* Hover overlay */}
              <div
                className="absolute inset-0 opacity-0 group-hover:opacity-100 transition-opacity duration-400 flex items-end p-5"
                style={{ background: "linear-gradient(to top, rgba(10,9,8,0.85) 0%, transparent 60%)" }}
              >
                <div>
                  <div
                    className="px-2.5 py-1 inline-block mb-2"
                    style={{
                      border: "1px solid rgba(196,189,182,0.3)",
                      borderRadius: "1px",
                    }}
                  >
                    <span style={{ fontFamily: "var(--font-ui)", fontSize: "8px", color: "rgba(196,189,182,0.6)", letterSpacing: "0.18em" }}>
                      {img.label}
                    </span>
                  </div>
                  <div style={{ fontFamily: "var(--font-ui)", fontSize: "10px", color: "rgba(196,189,182,0.4)", letterSpacing: "0.1em" }}>
                    GENERATED IN 7.8s
                  </div>
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}